### ISSUE TITLE
(Must) Visible pricing for events and student discount

### ISSUE THREAD

**Issue by AJGreaves** [AJGreaves/boardwalk-games-lesson-plan#5]
**User Story**

As a Student Gamer, I want to find clear information about upcoming events, pricing, student discounts, and opening hours, so I can plan my visit within my budget and time constraints.

**Acceptance Criteria**
- [ ] Clear and accurate pricing information for events is displayed and easy to find
- [ ] Student discount information stands out near pricing information
- [ ] Pricing and opening hours information is easily accessible from the homepage or main menu.

**Tasks**
- [ ] (Must) Display pricing for events using the provided rate information.
- [ ] (Must) Clearly display student discount information with the pricing for events. 
- [ ] (Must) Display opening hours with the provided schedule.
- [ ] (Must) Ensure the pricing and discount information is easily accessible, from the homepage and navigation bar.
