### ISSUE TITLE
(Must) Booking inquiry form

### ISSUE THREAD

**Issue by AJGreaves** [AJGreaves/boardwalk-games-lesson-plan#6]
**User Story**

As a Customer, I want to book a table or join an open game night using a simple booking inquiry form, so I can easily organise a group visit or a special occasion. 

**Acceptance Criteria**
- [ ] A booking inquiry form for private events or game nights is easy to find, and the form is simple and easy to use.
- [ ] The form includes all necessary fields to gather event details.

**Tasks**
- [ ] (Must) Implement a booking inquiry form on the website.
